events {}

http {
  server {
    listen 80;

    # Quản lý vòng đời link
    location /api/ {
      proxy_pass http://link:3000;
      proxy_set_header Host $host;
    }

    # Mọi đường dẫn còn lại là một mã ngắn cần chuyển hướng
    location / {
      proxy_pass http://redirect:3000;
      proxy_set_header Host $host;
      proxy_redirect off;
    }
  }
}
